swagger: '2.0'

# This is your document metadata
info:
  version: "1.6"
  title: "Docker Registry HTTP API"

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /v2:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description:
        Tells whether this Docker Registry instance supports
        Docker Registry HTTP API v2
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
        401:
          description: Unauthorized access
        404:
          description: Registry does not implement v2 of the API 
